
# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: dabao1955/kernel_build_action@main
      with:
          kernel-url: https://github.com/xiaomi-msm8953-devs/android_kernel_xiaomi_msm8953
          kernel-dir: msm-4.9
          kernel-branch: lineage-22.0
          config: msm8953-perf_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 12
          aosp-clang-version: r383902
          disable-lto: true
          anykernel3: true
